channels:
  - openeye
  - conda-forge
dependencies:
  - python=3.10
  - scikit-learn
  - pydantic
  - ca-certificates
  - openssl
  - pytest
  - pandas
  - black
  - plotly
  - jupyter
  - openeye-toolkits
  - rdkit
  - certifi
  - openff-toolkit
  - pytest-cov
  - codecov
  - pytest-console-scripts
  - pytest-timeout
  - pytest-xdist
