name: harbor
channels:
  - openeye
  - conda-forge
dependencies:
  - python=3.10
  - scikit-learn
  - pydantic
  - ca-certificates
  - openeye-toolkits
  - openssl
  - pytest
  - pandas
  - black
  - rdkit
  - openff-toolkit
